### ISSUE TITLE
I want implement something like your CodeWire, can u explain a little bit of your source code?

### ISSUE THREAD

**Issue by GuilhermeBorges3Ddev** [ayushk7/CodeWire#2]
Sorry to open a issue for this.
I wanna just a simple graph based on your project, not a copy.

**Comment by ayushk7** [comment]
The most important part of the app is algorithm used to convert visual code to text-based(javascript) code. The algorithm I used is slight modification of DFS, It starts traversing from the begin node and at each subsequent code it requests any input if required and then it moves to the next node.
You should see /javascript/VisualScriptToJavascript/VisualScriptToJavascript.js, There are two big switch statements there where first switch one statement is for execution nodes(nodes which direct the flow of the program like begin, Ifelse, forloop, print etc) and the second switch statement is for input nodes(like multiply, divide, add etc). What these switch statements does is: it generates valid javascript code(string) for the nodes and plugs appropriate variables/inputs if required.

Also for gui you can see javascript/Wiring/Wiring.js which manages wiring(connecting two nodes by bezier curve/wire).
Also javascript/Nodes/nodes.js contains details about each nodes visual representation(this file is huge).
Also note that get/set variable nodes are always treated specially.  


Now, if you want to make something similar you don't need to do all this crazy stuff from scratch, there are some other libraries and frameworks you can use which are definitely mature than my noob code.
1) Rete Js (https://rete.js.org/) (Web Based)
2) Ryven(https://ryven.org/) (For Python)
3) Litegraph Js(https://github.com/jagenjo/litegraph.js)

Also there are some other libraries also but I can't remember
