### ISSUE TITLE
Discord Invite Expired

### ISSUE THREAD

**Issue by d3is** [ayushk7/CodeWire#22]
Hi everyone! It looks like the Discord invite link has expired and I would love to start chatting with folks about the project and possibly contribute. Thanks!

**Comment by ayushk7** [comment]
Hi @d3is, the project is not being actively maintained as of now. I'm not sure if I'll open the discord server. Probably the github(issues/pull request) or email is the only way to connect or discuss now.

**Comment by ayushk7** [comment]
Just in case, I've enabled the github discussion you can post queries over there, if any.
