### ISSUE TITLE
is there a conact ?

### ISSUE THREAD

**Issue by L-o-o-t** [ayushk7/CodeWire#3]
contact email ?
How do you feel about one day, importing nodes from npm packages? Is there a list of stuff that needs to be done? so I can contribute I think ill start working on methods? what this really needs is the inspector.
I started a discord for it if you want to join. https://discord.gg/VuB2UjzqrK Can give you all permissions too.

**Comment by ayushk7** [comment]
hi, you can mail me at ayushkashyap.rock3@gmail.com, wasn't able to get the issue notif until it got closed

**Comment by L-o-o-t** [comment]
thank you I look forward working to together
